gryffindor = set(input().split())
ravenclaw = set(input().split())
slytherin = set(input().split())
hufflepuff = set(input().split())
res = set()
res = res.union(gryffindor)
res = res.union(ravenclaw)
res = res.union(slytherin)
res = res.union(hufflepuff)
print(res)